### ISSUE TITLE
Win10 update kills it again as at Dec 28 2018

### ISSUE THREAD

**Issue by megamind888** [adamwestman/driver-zboard-merc#4]
Was working fine with your fix but a major windows update a couple days ago killed it again and can not get it going with same code. It does give the "this driver is not digitally signed" error which is known but I can not get it installed. "a problem was encountered while attempting to add the driver to the store."

**Comment by adamwestman** [comment]
And did you make sure to repeat the step where you disable requirement for signed certificate through bios, before attempting the install again?

**Comment by megamind888** [comment]
AAAAAAA HAAAAA! Ok my bad. Please replace the "Usage" section on the main github page with something like this to help the fools like me:
![image](https://user-images.githubusercontent.com/5641461/50542753-aa712180-0b79-11e9-8d0a-9dca4314d965.png)

**Comment by megamind888** [comment]
Super big thank you from so many people you have no idea. I have an awesome Alloy Elite HyperX mechanical keyboard yet I am always using this old keyboard because that side custom keypad is sooo awesome and makes gaming so much better. Why doesn't everyone make these!? Inform Steelseries you have a fix maybe they will post on their site because that is where everyone first goes to fix this. Cheers dude no idea how you figured out how to fix this you rock.
